-- ======================================================
-- Create OLAP Schema (Oracle)
-- ======================================================

-- Switch to schema after creating user:
-- ALTER SESSION SET CURRENT_SCHEMA = CARESERVICES_OLAP;

-- ======================================================
-- Dimension Tables
-- ======================================================

CREATE TABLE DimEmployee (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255) NOT NULL,
    Address VARCHAR2(255),
    JobTitle VARCHAR2(255),
    EmployeeType VARCHAR2(255),
    SalaryRate NUMBER(10,2),
    ReportsTo NUMBER
);

CREATE TABLE DimClient (
    ClientID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255) NOT NULL,
    Address VARCHAR2(255),
    ContactInfo VARCHAR2(255)
);

CREATE TABLE DimService (
    ServiceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ServiceName VARCHAR2(255),
    Rate NUMBER(10,2),
    RequiresCertification CHAR(1) CHECK (RequiresCertification IN ('0', '1'))
);

CREATE TABLE DimAsset (
    AssetID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AssetType VARCHAR2(255),
    Location VARCHAR2(255),
    MonthlyRent NUMBER(10,2)
);

CREATE TABLE DimRenter (
    RenterID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255),
    EmergencyContact VARCHAR2(255),
    FamilyDoctor VARCHAR2(255)
);

-- ======================================================
-- Fact Tables
-- ======================================================

CREATE TABLE FactPayroll (
    PayrollID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimEmployeeID NUMBER NOT NULL,
    PayDate DATE NOT NULL,
    BaseSalary NUMBER(10,2) NOT NULL,
    OverTimePay NUMBER(10,2) NOT NULL,
    Deductions NUMBER(10,2) NOT NULL,
    NetPay NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_factpayroll_employee FOREIGN KEY (DimEmployeeID)
        REFERENCES DimEmployee(EmployeeID)
);

CREATE TABLE FactShifts (
    ShiftID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimEmployeeID NUMBER NOT NULL,
    StartTime DATE NOT NULL,
    EndTime DATE NOT NULL,
    IsOnCall CHAR(1) CHECK (IsOnCall IN ('0', '1')),
    CONSTRAINT fk_factshifts_employee FOREIGN KEY (DimEmployeeID)
        REFERENCES DimEmployee(EmployeeID)
);

CREATE TABLE FactAttendance (
    AttendanceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimEmployeeID NUMBER NOT NULL,
    FactShiftsID NUMBER NOT NULL,
    IsHoliday CHAR(1) CHECK (IsHoliday IN ('0', '1')),
    IsVacation CHAR(1) CHECK (IsVacation IN ('0', '1')),
    IsOnCall CHAR(1) CHECK (IsOnCall IN ('0', '1')),
    CONSTRAINT fk_factattendance_employee FOREIGN KEY (DimEmployeeID)
        REFERENCES DimEmployee(EmployeeID),
    CONSTRAINT fk_factattendance_shift FOREIGN KEY (FactShiftsID)
        REFERENCES FactShifts(ShiftID)
);

CREATE TABLE FactServiceAssignment (
    AssignedID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimEmployeeID NUMBER NOT NULL,
    DimServiceID NUMBER NOT NULL,
    ScheduledDate DATE NOT NULL,
    CONSTRAINT fk_factassign_employee FOREIGN KEY (DimEmployeeID)
        REFERENCES DimEmployee(EmployeeID),
    CONSTRAINT fk_factassign_service FOREIGN KEY (DimServiceID)
        REFERENCES DimService(ServiceID)
);

CREATE TABLE FactInvoice (
    InvoiceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimClientID NUMBER NOT NULL,
    DimServiceID NUMBER NOT NULL,
    InvoiceDate DATE NOT NULL,
    TotalAmount NUMBER(10,2) NOT NULL,
    IsPaid CHAR(1) CHECK (IsPaid IN ('0', '1')),
    CONSTRAINT fk_factinvoice_client FOREIGN KEY (DimClientID)
        REFERENCES DimClient(ClientID),
    CONSTRAINT fk_factinvoice_service FOREIGN KEY (DimServiceID)
        REFERENCES DimService(ServiceID)
);

CREATE TABLE FactServiceRegistration (
    RegistrationID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimClientID NUMBER NOT NULL,
    DimServiceID NUMBER NOT NULL,
    RegistrationDate DATE NOT NULL,
    CONSTRAINT fk_factreg_client FOREIGN KEY (DimClientID)
        REFERENCES DimClient(ClientID),
    CONSTRAINT fk_factreg_service FOREIGN KEY (DimServiceID)
        REFERENCES DimService(ServiceID)
);

CREATE TABLE FactDamageReport (
    ReportID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimAssetID NUMBER NOT NULL,
    ReportDate DATE NOT NULL,
    RepairCost NUMBER(10,2) NOT NULL,
    Description VARCHAR2(255),
    CONSTRAINT fk_factdamage_asset FOREIGN KEY (DimAssetID)
        REFERENCES DimAsset(AssetID)
);

CREATE TABLE FactRentalHistory (
    HistoryID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimAssetID NUMBER NOT NULL,
    DimRenterID NUMBER NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    RentAmount NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_factrental_asset FOREIGN KEY (DimAssetID)
        REFERENCES DimAsset(AssetID),
    CONSTRAINT fk_factrental_renter FOREIGN KEY (DimRenterID)
        REFERENCES DimRenter(RenterID)
);
