CREATE TABLE Employee (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255) NOT NULL,
    Address VARCHAR2(255),
    JobTitle VARCHAR2(255),
    EmployeeType VARCHAR2(255),
    SalaryRate NUMBER(10,2),
    ReportsTo NUMBER
);

CREATE TABLE Payment (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmployeeID NUMBER NOT NULL,
    PayDate TIMESTAMP NOT NULL,
    OverTimePay NUMBER(10,2) NOT NULL,
    Deductions NUMBER(10,2) NOT NULL,
    BasePay NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_payment_employee FOREIGN KEY (EmployeeID)
        REFERENCES Employee(EmployeeID)
);

CREATE TABLE Shift (
    ShiftID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmployeeID NUMBER NOT NULL,
    StartTime TIMESTAMP NOT NULL,
    EndTime TIMESTAMP NOT NULL,
    IsOnCall CHAR(1) CHECK (IsOnCall IN ('0', '1')),
    CONSTRAINT fk_shift_employee FOREIGN KEY (EmployeeID)
        REFERENCES Employee(EmployeeID)
);

CREATE TABLE Client (
    ClientID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255) NOT NULL,
    Address VARCHAR2(255),
    ContactInfo VARCHAR2(255)
);

CREATE TABLE ServiceType (
    ServiceTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ServiceName VARCHAR2(255),
    Rate NUMBER(10,2),
    RequiresCertification CHAR(1) CHECK (RequiresCertification IN ('0', '1'))
);

CREATE TABLE Service (
    ServiceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ServiceTypeID NUMBER NOT NULL,
    EmployeeID NUMBER NOT NULL,
    ClientID NUMBER NOT NULL,
    RegistrationDate TIMESTAMP NOT NULL,
    ScheduledDate TIMESTAMP NOT NULL,
    TotalAmount NUMBER(10,2) NOT NULL,
    IsPaid CHAR(1) CHECK (IsPaid IN ('0', '1')),
    CONSTRAINT fk_service_employee FOREIGN KEY (EmployeeID)
        REFERENCES Employee(EmployeeID),
    CONSTRAINT fk_service_servicetype FOREIGN KEY (ServiceTypeID)
        REFERENCES ServiceType(ServiceTypeID),
    CONSTRAINT fk_service_client FOREIGN KEY (ClientID)
        REFERENCES Client(ClientID)
);

CREATE TABLE Asset (
    AssetID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AssetType VARCHAR2(255),
    Location VARCHAR2(255),
    MonthlyRent NUMBER(10,2)
);

CREATE TABLE Renter (
    RenterID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255),
    EmergencyContact VARCHAR2(255),
    FamilyDoctor VARCHAR2(255)
);

CREATE TABLE AssetRent (
    AssetRentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AssetID NUMBER NOT NULL,
    RenterID NUMBER NOT NULL,
    StartDate TIMESTAMP NOT NULL,
    EndDate TIMESTAMP NOT NULL,
    CONSTRAINT fk_assetrent_asset FOREIGN KEY (AssetID)
        REFERENCES Asset(AssetID),
    CONSTRAINT fk_assetrent_renter FOREIGN KEY (RenterID)
        REFERENCES Renter(RenterID)
);