CREATE USER CARESERVICES_OLTP IDENTIFIED BY YourStrongPassword123!;
GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE VIEW TO CARESERVICES_OLTP;

CREATE USER CARESERVICES_OLAP IDENTIFIED BY YourStrongPassword123!;
GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE VIEW TO CARESERVICES_OLAP;

ALTER USER CARESERVICES_OLTP QUOTA UNLIMITED ON USERS;
ALTER USER CARESERVICES_OLAP QUOTA UNLIMITED ON USERS;